require 'phenax.localconfig'.initialize()
require 'phenax.repl'.initialize()
require 'phenax.rulerline'.initialize()
require 'phenax.folding'.initialize()
require 'phenax.search'.initialize()
require 'phenax.quickfix'.initialize()
